---
- hosts: all
  become: true
  vars:
    - openldap_base: 'dc=localhost'
    - pri_domain_name: localhost
    - openldap_populate: true
  roles:
    - role: ansible-etc-hosts
    - role: ansible-openldap
